# Generated by Django 4.2.19 on 2025-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="blog_images/"
            ),
        ),
    ]
